#ifndef EMULATOR_INSTRUCTION_FUNCTIONS_H
#define EMULATOR_INSTRUCTION_FUNCTIONS_H

#include "intel8080.h"
#include "cpu/8080/instructions/instructions.h"

void (*handlers[256])(State8080 *state) = {
    NoOp,	// 0X00
    UnimplementedInstruction,	// 0X01
    UnimplementedInstruction,	// 0X02
    UnimplementedInstruction,	// 0X03
    UnimplementedInstruction,	// 0X04
    DecrementRegisterB,	// 0X05
    MoveImmediateB,	// 0X06
    UnimplementedInstruction,	// 0X07
    UnimplementedInstruction,	// 0X08
    UnimplementedInstruction,	// 0X09
    UnimplementedInstruction,	// 0X0A
    UnimplementedInstruction,	// 0X0B
    UnimplementedInstruction,	// 0X0C
    UnimplementedInstruction,	// 0X0D
    MoveImmediateC,	// 0X0E
    UnimplementedInstruction,	// 0X0F

    UnimplementedInstruction,	// 0X10
    LoadRegisterPairImmediateDE,	// 0X11
    UnimplementedInstruction,	// 0X12
    IncrementRegisterPairDE,	// 0X13
    UnimplementedInstruction,	// 0X14
    UnimplementedInstruction,	// 0X15
    UnimplementedInstruction,	// 0X16
    UnimplementedInstruction,	// 0X17
    UnimplementedInstruction,	// 0X18
    AddRegisterPairDE,	// 0X19
    LoadAccumulatorIndirectDE,	// 0X1A
    UnimplementedInstruction,	// 0X1B
    UnimplementedInstruction,	// 0X1C
    UnimplementedInstruction,	// 0X1D
    UnimplementedInstruction,	// 0X1E
    UnimplementedInstruction,	// 0X1F

    UnimplementedInstruction,	// 0X20
    LoadRegisterPairImmediateHL,	// 0X21
    UnimplementedInstruction,	// 0X22
    IncrementRegisterPairHL,	// 0X23
    UnimplementedInstruction,	// 0X24
    UnimplementedInstruction,	// 0X25
    MoveImmediateH,	// 0X26
    UnimplementedInstruction,	// 0X27
    UnimplementedInstruction,	// 0X28
    AddRegisterPairHL,	// 0X29
    UnimplementedInstruction,	// 0X2A
    UnimplementedInstruction,	// 0X2B
    UnimplementedInstruction,	// 0X2C
    UnimplementedInstruction,	// 0X2D
    UnimplementedInstruction,	// 0X2E
    UnimplementedInstruction,	// 0X2F

    UnimplementedInstruction,	// 0X30
    LoadRegisterPairImmediateSP,	// 0X31
    UnimplementedInstruction,	// 0X32
    UnimplementedInstruction,	// 0X33
    UnimplementedInstruction,	// 0X34
    UnimplementedInstruction,	// 0X35
    MoveImmediateM,	// 0X36
    UnimplementedInstruction,	// 0X37
    UnimplementedInstruction,	// 0X38
    UnimplementedInstruction,	// 0X39
    UnimplementedInstruction,	// 0X3A
    UnimplementedInstruction,	// 0X3B
    UnimplementedInstruction,	// 0X3C
    UnimplementedInstruction,	// 0X3D
    UnimplementedInstruction,	// 0X3E
    UnimplementedInstruction,	// 0X3F

    UnimplementedInstruction,	// 0X40
    UnimplementedInstruction,	// 0X41
    UnimplementedInstruction,	// 0X42
    UnimplementedInstruction,	// 0X43
    UnimplementedInstruction,	// 0X44
    UnimplementedInstruction,	// 0X45
    UnimplementedInstruction,	// 0X46
    UnimplementedInstruction,	// 0X47
    UnimplementedInstruction,	// 0X48
    UnimplementedInstruction,	// 0X49
    UnimplementedInstruction,	// 0X4A
    UnimplementedInstruction,	// 0X4B
    UnimplementedInstruction,	// 0X4C
    UnimplementedInstruction,	// 0X4D
    UnimplementedInstruction,	// 0X4E
    UnimplementedInstruction,	// 0X4F

    UnimplementedInstruction,	// 0X50
    UnimplementedInstruction,	// 0X51
    UnimplementedInstruction,	// 0X52
    UnimplementedInstruction,	// 0X53
    UnimplementedInstruction,	// 0X54
    UnimplementedInstruction,	// 0X55
    UnimplementedInstruction,	// 0X56
    UnimplementedInstruction,	// 0X57
    UnimplementedInstruction,	// 0X58
    UnimplementedInstruction,	// 0X59
    UnimplementedInstruction,	// 0X5A
    UnimplementedInstruction,	// 0X5B
    UnimplementedInstruction,	// 0X5C
    UnimplementedInstruction,	// 0X5D
    UnimplementedInstruction,	// 0X5E
    UnimplementedInstruction,	// 0X5F

    UnimplementedInstruction,	// 0X60
    UnimplementedInstruction,	// 0X61
    UnimplementedInstruction,	// 0X62
    UnimplementedInstruction,	// 0X63
    UnimplementedInstruction,	// 0X64
    UnimplementedInstruction,	// 0X65
    UnimplementedInstruction,	// 0X66
    UnimplementedInstruction,	// 0X67
    UnimplementedInstruction,	// 0X68
    UnimplementedInstruction,	// 0X69
    UnimplementedInstruction,	// 0X6A
    UnimplementedInstruction,	// 0X6B
    UnimplementedInstruction,	// 0X6C
    UnimplementedInstruction,	// 0X6D
    UnimplementedInstruction,	// 0X6E
    MoveRegistersLA,	// 0X6F

    UnimplementedInstruction,	// 0X70
    UnimplementedInstruction,	// 0X71
    UnimplementedInstruction,	// 0X72
    UnimplementedInstruction,	// 0X73
    UnimplementedInstruction,	// 0X74
    UnimplementedInstruction,	// 0X75
    UnimplementedInstruction,	// 0X76
    MoveAccumulatorToMemoryHL,	// 0X77
    UnimplementedInstruction,	// 0X78
    UnimplementedInstruction,	// 0X79
    UnimplementedInstruction,	// 0X7A
    UnimplementedInstruction,	// 0X7B
    MoveRegistersHA,	// 0X7C
    UnimplementedInstruction,	// 0X7D
    UnimplementedInstruction,	// 0X7E
    UnimplementedInstruction,	// 0X7F

    UnimplementedInstruction,	// 0X80
    UnimplementedInstruction,	// 0X81
    UnimplementedInstruction,	// 0X82
    UnimplementedInstruction,	// 0X83
    UnimplementedInstruction,	// 0X84
    UnimplementedInstruction,	// 0X85
    UnimplementedInstruction,	// 0X86
    UnimplementedInstruction,	// 0X87
    UnimplementedInstruction,	// 0X88
    UnimplementedInstruction,	// 0X89
    UnimplementedInstruction,	// 0X8A
    UnimplementedInstruction,	// 0X8B
    UnimplementedInstruction,	// 0X8C
    UnimplementedInstruction,	// 0X8D
    UnimplementedInstruction,	// 0X8E
    UnimplementedInstruction,	// 0X8F

    UnimplementedInstruction,	// 0X90
    UnimplementedInstruction,	// 0X91
    UnimplementedInstruction,	// 0X92
    UnimplementedInstruction,	// 0X93
    UnimplementedInstruction,	// 0X94
    UnimplementedInstruction,	// 0X95
    UnimplementedInstruction,	// 0X96
    UnimplementedInstruction,	// 0X97
    UnimplementedInstruction,	// 0X98
    UnimplementedInstruction,	// 0X99
    UnimplementedInstruction,	// 0X9A
    UnimplementedInstruction,	// 0X9B
    UnimplementedInstruction,	// 0X9C
    UnimplementedInstruction,	// 0X9D
    UnimplementedInstruction,	// 0X9E
    UnimplementedInstruction,	// 0X9F

    UnimplementedInstruction,	// 0xA0
    UnimplementedInstruction,	// 0xA1
    UnimplementedInstruction,	// 0xA2
    UnimplementedInstruction,	// 0xA3
    UnimplementedInstruction,	// 0xA4
    UnimplementedInstruction,	// 0xA5
    UnimplementedInstruction,	// 0xA6
    UnimplementedInstruction,	// 0xA7
    UnimplementedInstruction,	// 0xA8
    UnimplementedInstruction,	// 0xA9
    UnimplementedInstruction,	// 0xAA
    UnimplementedInstruction,	// 0xAB
    UnimplementedInstruction,	// 0xAC
    UnimplementedInstruction,	// 0xAD
    UnimplementedInstruction,	// 0xAE
    UnimplementedInstruction,	// 0xAF

    UnimplementedInstruction,	// 0xB0
    UnimplementedInstruction,	// 0xB1
    UnimplementedInstruction,	// 0xB2
    UnimplementedInstruction,	// 0xB3
    UnimplementedInstruction,	// 0xB4
    UnimplementedInstruction,	// 0xB5
    UnimplementedInstruction,	// 0xB6
    UnimplementedInstruction,	// 0xB7
    UnimplementedInstruction,	// 0xB8
    UnimplementedInstruction,	// 0xB9
    UnimplementedInstruction,	// 0xBA
    UnimplementedInstruction,	// 0xBB
    UnimplementedInstruction,	// 0xBC
    UnimplementedInstruction,	// 0xBD
    UnimplementedInstruction,	// 0xBE
    UnimplementedInstruction,	// 0xBF

    UnimplementedInstruction,	// 0XC0
    UnimplementedInstruction,	// 0XC1
    JumpNotZero,	// 0XC2
    Jump,	// 0XC3
    UnimplementedInstruction,	// 0XC4
    PushBC,	// 0XC5
    UnimplementedInstruction,	// 0XC6
    UnimplementedInstruction,	// 0XC7
    UnimplementedInstruction,	// 0XC8
    Return,	// 0XC9
    UnimplementedInstruction,	// 0XCA
    UnimplementedInstruction,	// 0XCB
    UnimplementedInstruction,	// 0XCC
    Call,	// 0XCD
    UnimplementedInstruction,	// 0XCE
    UnimplementedInstruction,	// 0XCF

    UnimplementedInstruction,	// 0XD0
    UnimplementedInstruction,	// 0XD1
    UnimplementedInstruction,	// 0XD2
    Out,	// 0XD3
    UnimplementedInstruction,	// 0XD4
    PushDE,	// 0XD5
    UnimplementedInstruction,	// 0XD6
    UnimplementedInstruction,	// 0XD7
    UnimplementedInstruction,	// 0XD8
    UnimplementedInstruction,	// 0XD9
    UnimplementedInstruction,	// 0XDA
    UnimplementedInstruction,	// 0XDB
    UnimplementedInstruction,	// 0XDC
    UnimplementedInstruction,	// 0XDD
    UnimplementedInstruction,	// 0XDE
    UnimplementedInstruction,	// 0xDF

    UnimplementedInstruction,	// 0xE0
    PopH,	// 0xE1
    UnimplementedInstruction,	// 0xE2
    UnimplementedInstruction,	// 0xE3
    UnimplementedInstruction,	// 0xE4
    PushHL,	// 0xE5
    UnimplementedInstruction,	// 0xE6
    UnimplementedInstruction,	// 0xE7
    UnimplementedInstruction,	// 0xE8
    UnimplementedInstruction,	// 0xE9
    UnimplementedInstruction,	// 0xEA
    ExchangeHL_DE,	// 0xEB
    UnimplementedInstruction,	// 0xEC
    UnimplementedInstruction,	// 0xED
    UnimplementedInstruction,	// 0xEE
    UnimplementedInstruction,	// 0xEF

    UnimplementedInstruction,	// 0xF0
    UnimplementedInstruction,	// 0xF1
    UnimplementedInstruction,	// 0xF2
    UnimplementedInstruction,	// 0xF3
    UnimplementedInstruction,	// 0xF4
    UnimplementedInstruction,	// 0xF5
    UnimplementedInstruction,	// 0xF6
    UnimplementedInstruction,	// 0xF7
    UnimplementedInstruction,	// 0xF8
    UnimplementedInstruction,	// 0xF9
    UnimplementedInstruction,	// 0xFA
    UnimplementedInstruction,	// 0xFB
    UnimplementedInstruction,	// 0xFC
    UnimplementedInstruction,	// 0xFD
    CompareImmediate,	// 0xFE
    UnimplementedInstruction    // 0xFF
};
#endif
